In [1]:
import numpy as np
import pandas as pd
from datetime import datetime
from time import time
import itertools
from matplotlib.ticker import NullFormatter
import scipy.stats as stats
from scipy.spatial.distance import pdist, squareform, cdist
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.metrics import silhouette_score, silhouette_samples
from sklearn.manifold import TSNE
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline
import matplotlib.cm as cm
import seaborn as sn

from sportsreference.nba.boxscore import Boxscore
from sportsreference.nba.roster import Roster, Player
from sportsreference.nba.schedule import Schedule
from sportsreference.nba.teams import Teams

import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

In [8]:
df_season = pd.read_csv('data/2nba_player_stats_by_season.csv')

/home/luke/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3147: DtypeWarning: Columns (102) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [9]:
df_season.head()

,id,and_ones,assist_percentage,assists,block_percentage,blocking_fouls,blocks,box_plus_minus,center_percentage,defensive_box_plus_minus,...,age,avg_salary,years_played,year_list,current_player,contract_total,contract_length,current_salary,current_avg_salary,current_team
0,bareajo01 2007,NaN,20.4,24.0,0.4,NaN,1.0,-5.2,0,-2.3,...,22.5,29479.857143,14,"['2006-07', '2007-08', '2008-09', '2009-10', '...",False,NaN,NaN,NaN,NaN,NaN
1,bareajo01 2008,NaN,20.6,58.0,0.2,NaN,1.0,-1.9,0,-0.2,...,23.5,49104.000000,14,"['2006-07', '2007-08', '2008-09', '2009-10', '...",False,NaN,NaN,NaN,NaN,NaN
2,bareajo01 2009,NaN,26.4,269.0,0.2,NaN,5.0,-1.5,0,-1.1,...,24.5,107142.857143,14,"['2006-07', '2007-08', '2008-09', '2009-10', '...",False,NaN,NaN,NaN,NaN,NaN
3,bareajo01 2010,NaN,26.1,258.0,0.3,NaN,6.0,-1.3,0,-0.7,...,25.5,118392.857143,14,"['2006-07', '2007-08', '2008-09', '2009-10', '...",False,NaN,NaN,NaN,NaN,NaN
4,bareajo01 2011,NaN,31.2,317.0,0.0,NaN,1.0,-0.5,0,-1.0,...,26.5,129642.857143,14,"['2006-07', '2007-08', '2008-09', '2009-10', '...",False,NaN,NaN,NaN,NaN,NaN

In [12]:
df_season = df_season.dropna(how='all', axis=0)

In [18]:
drop_lst = []

for col in df_season.columns:
    unique = df_season[col].unique()
    val = len(unique)
    if val < 20:
        drop_lst.append(str(col))
        print(f'{col}: has {val} values')
        print(f'Values include:')
        print(f'     {unique}')

print(f'Drop List: {drop_lst}')

and_ones: has 1 values
Values include:
     [nan]
blocking_fouls: has 1 values
Values include:
     [nan]
center_percentage: has 1 values
Values include:
     [0]
dunks: has 1 values
Values include:
     [nan]
half_court_heaves: has 17 values
Values include:
     [ 0.  2.  1.  3.  6. nan 14.  9.  4.  5.  8.  7. 10. 11. 18. 13. 12.]
half_court_heaves_made: has 4 values
Values include:
     [ 0.  1. nan  2.]
lost_ball_turnovers: has 1 values
Values include:
     [nan]
net_plus_minus: has 1 values
Values include:
     [nan]
offensive_fouls: has 1 values
Values include:
     [nan]
on_court_plus_minus: has 1 values
Values include:
     [nan]
other_turnovers: has 1 values
Values include:
     [nan]
passing_turnovers: has 1 values
Values include:
     [nan]
percentage_field_goals_as_dunks: has 1 values
Values include:
     [nan]
percentage_of_three_pointers_from_corner: has 1 values
Values include:
     [nan]
percentage_shots_three_pointers: has 1 values
Values include:
     [nan]
percentage_shots_two_pointers: has 1 values
Values include:
     [nan]
point_guard_percentage: has 1 values
Values include:
     [0]
points_generated_by_assists: has 1 values
Values include:
     [nan]
position: has 11 values
Values include:
     ['PG' 'SF' 'C' 'SG' 'PF' 'C,PF' nan 'C,SF' 'PF,SF' 'PG,SG' 'SF,SG']
power_forward_percentage: has 1 values
Values include:
     [0]
shooting_fouls: has 1 values
Values include:
     [nan]
shooting_fouls_drawn: has 1 values
Values include:
     [nan]
shooting_guard_percentage: has 1 values
Values include:
     [0]
shots_blocked: has 1 values
Values include:
     [nan]
small_forward_percentage: has 1 values
Values include:
     [0]
take_fouls: has 1 values
Values include:
     [nan]
three_point_shot_percentage_from_corner: has 1 values
Values include:
     [nan]
three_pointers_assisted_percentage: has 1 values
Values include:
     [nan]
two_pointers_assisted_percentage: has 1 values
Values include:
     [nan]
current_player: has 2 values
Values include:
     [False  True]
contract_length: has 7 values
Values include:
     [nan  2.  3.  1.  4.  6.  5.]
Drop List: ['and_ones', 'blocking_fouls', 'center_percentage', 'dunks', 'half_court_heaves', 'half_court_heaves_made', 'lost_ball_turnovers', 'net_plus_minus', 'offensive_fouls', 'on_court_plus_minus', 'other_turnovers', 'passing_turnovers', 'percentage_field_goals_as_dunks', 'percentage_of_three_pointers_from_corner', 'percentage_shots_three_pointers', 'percentage_shots_two_pointers', 'point_guard_percentage', 'points_generated_by_assists', 'position', 'power_forward_percentage', 'shooting_fouls', 'shooting_fouls_drawn', 'shooting_guard_percentage', 'shots_blocked', 'small_forward_percentage', 'take_fouls', 'three_point_shot_percentage_from_corner', 'three_pointers_assisted_percentage', 'two_pointers_assisted_percentage', 'current_player', 'contract_length']

In [19]:
df_season = df_season.drop(['and_ones', 'blocking_fouls', 'dunks', 'lost_ball_turnovers',
'net_plus_minus', 'offensive_fouls', 'on_court_plus_minus',
'other_turnovers', 'passing_turnovers', 'percentage_field_goals_as_dunks',
'percentage_of_three_pointers_from_corner', 'percentage_shots_three_pointers',
'percentage_shots_two_pointers', 'points_generated_by_assists',
'shooting_fouls', 'shooting_fouls_drawn', 'shots_blocked',
'take_fouls', 'team_abbreviation', 'three_point_shot_percentage_from_corner',
'three_pointers_assisted_percentage', 'two_pointers_assisted_percentage',
'age', 'center_percentage', 'point_guard_percentage',
'power_forward_percentage', 'shooting_guard_percentage',
'small_forward_percentage', 'year', 'player_id'], axis=1)